pbuild/pandoc changes for algorithms

diff --git a/bin/pbpurge b/bin/pbpurge
--- a/bin/pbpurge
+++ b/bin/pbpurge
@@ -1,8 +1,7 @@
 #!/bin/sh
 
 # ENV must contain PINBOARD_AUTH_TOKEN, found at https://pinboard.in/settings/password
-[[ "$PINBOARD_AUTH_TOKEN" ]] || echo "Error: No PINBOARD_AUTH_TOKEN defined." &&
-                                echo "Find yours at https://pinboard.in/settings/password." && exit 1
+[[ "$PINBOARD_AUTH_TOKEN" ]] || echo "Error: No PINBOARD_AUTH_TOKEN defined." && echo "Find yours at https://pinboard.in/settings/password." && exit 1
 
 # display in frightening yellow
 function shw_warn { printf '\033[1;33m'"$1"'\033[0m'; }
